buildscripts/switch_rules, tools/.gitignore
Sorry, thought I had this committed before the last PR. Fix was in the devkitA64 alpha4 builds
=> Build fixes

nx/source/runtime/env.c, nx/source/runtime/init.c, nx/source/runtime/switch_crt0.s
=> Restore initial sp on application exit

nx/include/switch.h, nx/include/switch/services/audout.h, nx/source/services/audout.c
Basic audio output support via "audout:u" service.
=> Initial audio support

nx/source/runtime/newlib.c
Same as the ctrulib implementation, just svcSleepThread with usec -> nsec
=> Add usleep

nx/include/switch/services/hid.h, nx/source/services/hid.c
Thought I had this added but I guess not, only the mouse buttons were readable.
=> Add hidMouseRead, allows mouse position/velocity/scrollwheel velocity to be fetched

nx/include/switch/services/sm.h
Also adds domain support to sm.h.
=> Add new domain handling commands, fix existing ones, other bugfixes.

nx/include/switch/kernel/mutex.h, nx/source/kernel/mutex.c
I haven't tested the implementation yet, so be careful about merging this. I'll test it soon.
=> mutex: Add TryLock() variants.

nx/include/switch/services/irs.h, nx/source/services/irs.c
=> [irs] Name image transfer config variables

nx/source/runtime/devices/socket.c
This sorts out non blocking sockets.
=> add socket flags translation

nx/include/switch/services/lr.h, nx/source/services/lr.c
Adds all of the LR path Get/Setters, missing Manager->CheckStorage and most of RegisteredLocationResolver. Also missing all of AddOnContentLocationResolver.
=> Add support for some LR commands.

nx/Makefile
need this for making pacman packages
=> add $DESTDIR for packaging

nx/include/switch/services/set.h, nx/source/services/set.c
Title. Let me know if I need to make any changes.
=> Add setGetSerialNumber

nx/include/switch/services/set.h, nx/source/services/set.c
- setsysGetLockScreenFlag(u8 *out);
- setsysGetConsoleInformationUploadFlag(u8 *out);
- setsysGetAutomaticApplicationDownloadFlag(u8 *out);
- setsysGetNfcEnableFlag(u8 *out);
- setsysGetWirelessLanEnableFlag(u8 *out);
- setsysGetBluetoothEnableFlag(u8 *out);
=> Add some setsysGet* functions

nx/include/switch/services/ns.h, nx/source/services/ns.c
- nsGetTotalSpaceSize
- nsGetFreeSpaceSize
=> Add nsGetSpace commands

nx/include/switch.h, nx/include/switch/kernel/semaphore.h, nx/source/kernel/semaphore.c
Implement basic semaphore, no sem_post (yet)
=> Add Semaphore

nx/include/switch/services/ncm.h, nx/source/services/ncm.c
This is based on https://github.com/switchbrew/libnx/pull/104/ with several additions of my own.
=> Added ncm commands

nx/include/switch.h, nx/source/services/ncm.c
Added ncm to switch.h and fixed wrong order in ncmContentMetaDatabaseListApplication
=> Minor ncm fixes

nx/include/switch/services/fs.h, nx/source/services/fs.c
Just a note: I didn't add any comments since none of the other commands/functions don't have any.
=> Add fsFsCleanDirectoryRecursively

nx/include/switch/services/ncm.h, nx/source/services/ncm.c
Tested each one of these, all work as expected.
=> Add ncmContentStorage functions needed for writing content

nx/include/switch/services/fs.h, nx/source/services/fs.c
Implemented fsOpenBisFilesystem()
=> Wrapped and implemented fsOpenBisFilesystem()

nx/include/switch/kernel/rwlock.h, nx/source/kernel/rwlock.c
Rwlock didn't have an init routine, i was having some pretty wild undefined behaviours
=> Fix rwlock init

nx/include/switch/services/fs.h, nx/source/services/fs.c
Actually works now instead of always returning port remote dead
Thanks @misson20000 for finding out the switchbrew parameters for it were wrong
=> Fix fsOpenFileSystem

nx/include/switch/arm/thread_context.h, nx/include/switch/kernel/svc.h, nx/include/switch/kernel/thread.h, nx/source/kernel/svc.s, nx/source/kernel/thread.c
=> Implement svcGetThreadContext3+threadDumpContext and svcSetDebugThreadContext, other changes

nx/include/switch/services/hid.h, nx/source/services/hid.c
Adds the structs that SixAxis sensor states use in the controller structs. ~~I don't have code for reading them yet since I'm not sure how to select which layout I should be using yet.~~
=> hid: Add SixAxis sensor support

nx/include/switch/runtime/devices/usb_comms.h, nx/include/switch/services/usb.h, nx/source/runtime/devices/usb_comms.c, nx/source/services/usb.c
=> Refactor usb:ds, add 5.0.0+ support to usbComms.

nx/source/runtime/devices/socket.c
=> Reduce usage of malloc in select and poll. Fix poll not acceping -1 fds

nx/include/switch/kernel/virtmem.h, nx/source/kernel/thread.c, nx/source/kernel/virtmem.c
=> virtmem: Fix stack region mapping on 1.0.0

nx/include/switch.h, nx/include/switch/kernel/barrier.h, nx/include/switch/kernel/semaphore.h, nx/source/kernel/barrier.c
Pretty basic barrier implementation using semaphores, needed a good way to monitor threads so hopefully others can use it in the future.  Just basic barrierInit and barrierWait functions, no attributes.
=> barrier implementation using semaphores

nx/include/switch/services/hid.h
solves the SL/SR part of issue https://github.com/switchbrew/libnx/issues/206
=> support SL/SR buttons on right JoyCons

nx/include/switch.h, nx/include/switch/services/ldr.h, nx/include/switch/services/ns.h, nx/include/switch/services/pm.h, nx/include/switch/services/ro.h, nx/source/services/ldr.c, nx/source/services/ns.c, nx/source/services/pm.c, nx/source/services/ro.c
This PR adds ro:dmnt, and fully fleshes out ns:dev, pm:dmnt, pm:shell. It also adds ldr:ro, since that was apparently missing..
=> Implement various services for debug monitor usage.

nx/include/switch/services/nifm.h, nx/source/services/nifm.c
This pull request adds in a few more functions related to the nifm sysmodule. It allows checking to see if a system is using wireless / ethernet connections, and it can halt / resume all connections.
=> Add in more NIFM functionality

nx/include/switch/kernel/svc.h
Updated to match information provided in yuzu-emu/yuzu#1858
=> Fix svcSleepThread definition

nx/external/bsd/include/net/if.h
=> Fixed ifr_flags type by introducing ifr_flagshigh (fixes #248)

nx/include/switch.h, nx/include/switch/applets/error.h, nx/source/applets/error.c
Full support for error-applet.
=> Error applet

nx/include/switch/services/spl.h, nx/source/services/spl.c
=> spl: fix cryptAesCtr definition

nx/include/switch/runtime/devices/fs_dev.h, nx/source/runtime/devices/fs_dev.c
As per title. stdio currently doesn't offer a neat way of doing this.
=> Added fsdevDeleteDirectoryRecursively

nx/include/switch/services/ncm.h, nx/source/services/ncm.c
Implements ncm::IContentMetaDatabase->Cmd18
=> ncm: add ncmContentMetaDatabaseGetAttributes

nx/include/switch/services/i2c.h, nx/source/services/i2c.c
Also make buf const in SendAuto.
=> i2c: add ReceiveAudo and ExecuteCommandList

nx/source/services/fs.c
=> Fix fsFsCreateFile command parameters

nx/source/services/hidsys.c
Fix a copy/paste issue in hidsysSetNotificationLedPattern
=> hidsysSetNotificationLedPattern cleanup

nx/include/switch/kernel/svc.h, nx/source/kernel/detect.c, nx/source/kernel/random.c, nx/source/kernel/virtmem.c, nx/source/runtime/init.c, nx/source/runtime/newlib.c
Adds InfoType + SystemInfoType enums for IDs.
Also adds TickCountInfo, InitialProcessIdRangeInfo, PhysicalMemoryInfo enums for SubIDs.
=> Add enums for GetInfo/GetSystemInfo

nx/include/switch/services/pm.h, nx/source/services/pm.c
Same deal as sm stuff earlier.
=> pm: add getters for pminfo, pmshell

nx/include/switch/services/ldr.h, nx/source/services/ldr.c
=> ldr: add getters for shell/dmnt/pm

nx/source/services/ldr.c
=> ldr: fix getter error

nx/include/switch/services/fs.h, nx/source/services/fs.c
=> Added fsDeleteSaveDataFileSystemBySaveDataSpaceId

nx/include/switch/display/binder.h, nx/source/display/binder.c, nx/source/display/native_window.c
This is useful if you want to connect to "dispdrv" for example.
=> Make it possible to use the binder API with an arbitrary service

nx/include/switch/services/fs.h, nx/source/services/fs.c
As per title. Needed for NCM reimpl.
=> Implement fsOpenGameCardFileSystem

nx/include/switch/services/fs.h, nx/source/services/fs.c
Another day, another fs PR. As usual, needed for NCM.
=> Implement various SaveDataExtraData commands

nx/include/switch/services/fs.h, nx/source/services/fs.c
fsOpenCustomStorageFileSystem
fsExtendSaveDataFileSystem
fsSetGlobalAccessLogMode
fsGetGlobalAccessLogMode
=> Add some FS commands

nx/include/switch/nacp.h
Information based off of switchbrew.org: https://switchbrew.org/wiki/NACP_Format#Title_Entry
=> Filled in missing NacpStruct fields

nx/include/switch/services/ncm.h
=> Adjust NcmApplicationMetaExtendedHeader for 9.0.0

nx/include/switch/services/bpc.h, nx/include/switch/services/clkrst.h, nx/include/switch/services/fspr.h, nx/include/switch/services/gpio.h, nx/include/switch/services/i2c.h, nx/include/switch/services/ldr.h, nx/include/switch/services/pcv.h, nx/include/switch/services/psc.h, nx/include/switch/services/smm.h, nx/include/switch/services/spsm.h, nx/include/switch/services/vi.h, nx/source/services/bpc.c, nx/source/services/clkrst.c, nx/source/services/fsldr.c, nx/source/services/fspr.c, nx/source/services/gpio.c, nx/source/services/i2c.c, nx/source/services/ldr.c, nx/source/services/lr.c, nx/source/services/pcv.c, nx/source/services/psc.c, nx/source/services/smm.c, nx/source/services/spsm.c, nx/source/services/vi.c
This updates:
-gpio
-spsm
-pcv
-clkrst
-bpc
-fsp-pr
-fsp-ldr
-i2c
-psc:m
-sm:m
-ldr:*
-vi:*
=> Update services Atmosphere uses for new-ipc

nx/include/switch/services/ldr.h, nx/include/switch/services/ro.h, nx/source/services/ldr.c, nx/source/services/ro.c
Better matches actual loader API.
=> ldr: update names

nx/include/switch.h, nx/include/switch/applets/psel.h, nx/source/applets/psel.c
Everything was tested working fine (all modes and flags)
=> Add psel (playerSelect) support

nx/include/switch/services/set.h, nx/source/services/set.c
Hi, using [switchbrew docs](https://switchbrew.org/wiki/Settings_services#set:cal) I added the set:cal service and a few of the functions that were documented.
I have tested them and they work.
Let me know if you would like me to rename anything or move the functions around.
=> Add set:cal service with a few cal functions.

nx/include/switch.h, nx/include/switch/services/caps.h, nx/include/switch/services/capsa.h, nx/include/switch/services/grc.h, nx/source/services/capsa.c
I'm almost certain some of these are deprecated on newer versions.
=> added caps:a

nx/include/switch/services/lbl.h, nx/source/services/lbl.c
I arranged the existing commands by id.
=> lbl: more commands

nx/include/switch/services/fs.h, nx/include/switch/services/hid.h, nx/include/switch/services/set.h, nx/include/switch/services/time.h, nx/source/services/set.c
I'm not so sure about how the Edid struct is parsed, it has several odd-sized members and the official spec has some dynamic field types, so I went by what was present in my save... Otherwise I tagged all added struct members to the best of my ability but many are unknown.
=> Complete and correct all Settings calls

nx/include/switch/applets/swkbd.h
Work out some more keyboard types
=> More keyboard types

nx/include/switch.h, nx/include/switch/runtime/ringcon.h, nx/source/runtime/ringcon.c
Needs testing, and various adjustments after testing.
=> Added ringcon.

nx/include/switch.h, nx/include/switch/kernel/svc.h, nx/include/switch/services/fsldr.h, nx/include/switch/services/ldr.h, nx/include/switch/services/pgl.h, nx/source/kernel/svc.s, nx/source/services/fsldr.c, nx/source/services/fspr.c, nx/source/services/ldr.c, nx/source/services/pgl.c
Note: This should not be merged yet.
pgl will still need to be added to make creport function correctly.
=> 10.0.0 Atmosphere support

nx/include/switch/services/lr.h, nx/include/switch/services/pgl.h, nx/include/switch/services/pm.h, nx/source/services/lr.c, nx/source/services/pgl.c, nx/source/services/pm.c
Implements the full api for the new pgl service.
Don't merge yet, will also commit service commands that pgl sysmodule needs to use soon.
=> pgl: implement full api

nx/include/switch/services/set.h, nx/source/services/set.c
=> set: fix GetGyroscopeOffset

nx/include/switch/kernel/mutex.h, nx/source/kernel/mutex.c
This is much more optimized code, and matches Nintendo's critical section precisely.
Ported from libstratosphere.
=> mutex: rewrite to optimize

nx/include/switch/services/psm.h, nx/source/services/psm.c
Adds a few more psm functions relating to battery charging.
=> psm: Add more battery functions

nx/include/switch/services/gpio.h, nx/source/services/gpio.c
This fixes the service for 7.0.0+ (heh), and adds most of the other gpio pad accessors.
=> gpio: implement majority of the service

nx/source/services/gpio.c
=> gpio: loosen sysver restriction on OpenSession

nx/source/display/native_window.c, nx/source/kernel/condvar.c, nx/source/kernel/virtmem.c, nx/source/nvidia/fence.c, nx/source/runtime/devices/fs_dev.c, nx/source/runtime/devices/romfs_dev.c, nx/source/services/applet.c, nx/source/services/grc.c, nx/source/services/sm.c
This is needed for 11.x erpt/error context changes.
=> results: use R_VALUE for comparisons

nx/include/switch/kernel/svc.h
probably rename this commit, whoops
=> svc: add new InfoType_FreeThreadCount

nx/source/services/avm.c
=> avm: fix more merge errors

nx/include/switch/runtime/hosversion.h, nx/source/runtime/hosversion.c, nx/source/services/ro.c, nx/source/services/sm.c
For both ro:dmnt, sm::DetachClient.
=> add hosversionIsAtmosphere

nx/include/switch/services/fs.h, nx/source/services/fs.c
A future PR will probably be made for fsdevMountHost(), once stuff works and we've discussed how to handle options.
=> fs: add fsOpenHostFileSystem(WithOption)

nx/source/services/bsd.c
=> bsd: fix bsdRegisterClient

nx/include/switch.h, nx/include/switch/services/htcs.h, nx/source/services/htcs.c
Don't merge yet, needs testing (which will necessitate writing host pc code...)
Code should be reviewed in the meantime, though.
=> htcs: implement hipc bindings

nx/include/switch/services/friends.h, nx/source/services/friends.c
This pull request adds the ability to open the friend:* services and get the friend code, along with other items.
**Hardware Test** 
**Tested Source Code**
[Friend-Code.zip](https://github.com/switchbrew/libnx/files/6272279/Friend-Code.zip)
=> friends: ability to get Friend Code

nx/include/switch/services/hid.h
I recently did some RE on touch gestures with the help of a nro I made. I have found that those values where incorrect.
=> hid: Correct some gesture errors

nx/include/switch/services/btdrv.h, nx/include/switch/services/btdrv_types.h, nx/source/services/btdrv.c
Rebased version of #540 with an additional commit.
=> Bluetooth pr rebased

nx/source/runtime/util/inet_addr.c
Wrote this patch yesterday but hadn't tested it yet. There was some hesitancy towards using sscanf so this may be the preferred solution over #558.
This fixes #557.
=> Fix inet_pton by passing in base instead of getting it out

nx/source/services/ro.c
The command takes a process ID:
https://github.com/Atmosphere-NX/Atmosphere/blob/master/libraries/libstratosphere/include/stratosphere/ro/impl/ro_ro_interface.hpp#L27
=> Fix ldr:ro/ro:1 initialization

nx/include/switch/runtime/devices/console.h, nx/source/runtime/devices/console.c, nx/source/runtime/devices/console_sw.c
This supports the escape sequences used by fmtlib
=> Add support for SGR 38 and 48

nx/include/switch/kernel/svc.h, nx/include/switch/services/bpc.h, nx/include/switch/services/pm.h, nx/source/arm/cache.s, nx/source/services/bpc.c, nx/source/services/pm.c
This PR is WIP, tracking changes to libnx necessary for atmosphere to support 14.0.0.
=> Baseline changes for 14.0.0 support.

nx/include/switch/kernel/svc.h, nx/include/switch/runtime/env.h, nx/source/kernel/svc.s, nx/source/runtime/env.c
This PR shouldn't be merged yet, and is for getting in anything libnx needs for 15.0.0 support.
=> Add changes for baseline 15.0.0 support

nx/include/switch/services/btdrv.h, nx/include/switch/sf/cmif.h, nx/source/applets/web.c, nx/source/services/applet.c
Type mismatches picked up by gcc 13
=> fix type mismatches

nx/include/switch/services/pctl.h, nx/source/services/pctl.c
I'm trying to get Qlaunch working. So I made a few HW test and I needed these functions.
=> service: pctl: Implement functions used by Qlaunch

nx/include/switch/sf/service.h
This fixes the new static assert compat with C++.
=> sf: fix service macro C++ compat

nx/include/switch/services/fs.h, nx/source/services/fs.c
These are all needed for latest 17.x changes in atmosphere.
=> erpt: add FS commands needed for SubmitFsInfo()

nx/source/crypto/sha256.c, nx/source/runtime/util/inet_addr.c, nx/source/services/btdrv.c
This fixes some issues so that libnx correctly compiles with gcc15.
=> Fixes for GCC 15

nx/include/switch/runtime/devices/console.h, nx/source/runtime/devices/console.c, nx/source/runtime/devices/console_sw.c
* Simplifies ansi escape sequence code allowing escape sequences to be split across multiple writes
* Use 1-based co-ordinates consistently internally and in window API.
=> refactor console code for better ansi escape-code handling
