tools/Makefile, tools/elf2nro.c
Loads correctly with Pegaswitch, about as bare-minimum as elf2nso (no relocation/linking to NSOs, just loads in the sections and sets header info correctly). Probably doesn't work outright with crt0 (nor should it, tbh) but it's useful for building loadable code with devkitA64+libnx.
=> Elf->NRO support

crt0/switch_crt0.s, tools/elf2nro.c
Did some more testing (and forgot to commit some code...), the RX+R+RW sections are guaranteed to be located in sequence, so it's best to use the vaddr as the file writing location. ~~With the current crt0, however, this causes the NRO0 header to overwrite some of .text, can be avoided with some padding though.~~ crt0 has been adjusted to account for the NRO header.
=> elf2nro tweaks

buildscripts/lib/switch.specs, nx/Makefile, nx/include/switch/kernel/mutex.h, nx/include/switch/kernel/thread.h, nx/include/switch/result.h, nx/include/switch/services/fatal.h, nx/source/internal.h, nx/source/kernel/mutex.c, nx/source/kernel/thread.c, nx/source/services/fatal.c, nx/source/system/init.c, nx/source/system/newlib.c, nx/source/system/readtp.s
All of this is now done, however it's completely untested by me, since I can't run switch code (yet?)
Please test before merging.
=> devkitA64 alpha 5 updates (locks, TLS, etc) {TEST BEFORE MERGE}

nx/include/switch/services/bsd.h, nx/source/services/bsd.c
bsdSendTo definitely works, bsdSetSockOpt I haven't gotten any returns in Errno except 22 (Invalid argument), but it's not erroring from IPC at least. I was testing with UDP though, wanted to set SO_BROADCAST but maybe it's just not supported.
=> Add bsdSendTo and bsdSetSockOpt

nx/include/switch/services/hid.h, nx/source/services/hid.c
Example of usage:
```
// Retrieve only raw left output from Player 1
hidSetControllerLayout(CONTROLLER_PLAYER_1, LAYOUT_LEFT);
while(1)
{
hidScaninput();
if (hidKeysHeld(CONTROLLER_PLAYER_1) & KEY_DOWN)
printf("P1 left controller is held down\n");
if (hidKeysDown(CONTROLLER_HANDHELD) & KEY_A)
printf("Handheld pressed A!\n");
if ((hidMouseButtonsHeld() & MOUSE_LEFT) && hidKeyboardHeld(KBD_W))
printf("Pyro main detected!\n");
if (hidKeyboardModifierUp(KBD_MOD_CAPSLOCK))
printf("caps lock finally released\n");
if (hidKeysDown(CONTROLLER_HANDHELD) & KEY_TOUCH) {
touchPosition pos;
printf("Touches at:\n");
for (int i = 0; i < hidTouchCount(); i++) {
hidTouchRead(&pos, i);
printf("Touch index #%u: %u, %u\n", i, pos.px, pos.py);
}
}
}
```
Keyboard keys are handled with the key passed in due to …
=> HID Shared Memory - Structures + key held/down/up implementation

nx/include/switch/services/vi.h, nx/source/gfx/gfx.c, nx/source/services/vi.c
vi:m is able to create its own managed layers without AppletAE/AppletAO. Also fixed a typo in gfx.c.
=> vi:m ManagedLayer support

nx/Makefile
When using make install on libnx, it doesn't include the default icon when putting the libnx files in a .tar.bz2. This causes compiling on any libnx examples to error saying that the default icon couldn't be found.
=> default icon now included with libnx on make install

nx/source/runtime/devices/usb_comms.c
Previously g_usbComms_endpoint_out_buffer wouldnt be freed in usbCommsExit, as g_usbComms_endpoint_out would be set to NULL before the conditional check.
I've opted to remove the checks for null before calling free, since it's unnecessary, but can add them back with the corrected conditional if that's preferable.
=> usb_comms: Correct scenarios when freeing the endpoint out buffer

nx/include/switch/services/hid.h, nx/source/services/hid.c
Sample of usage:
```
JoystickPosition lStick;
JoystickPosition rStick;
float lStickX;
float lStickY;
float rStickX;
float rStickY;
while(appIsAliveOrSomething())
{
hidScanInput();
hidJoystickRead(&lStick, CONTROLLER_HANDHELD, JOYSTICK_LEFT);
hidJoystickRead(&rStick, CONTROLLER_HANDHELD, JOYSTICK_RIGHT);
lStickX = (float)lStick.dx / JOYSTICK_MAX;
lStickY = (float)lStick.dy / JOYSTICK_MAX;
rStickX = (float)rStick.dx / JOYSTICK_MAX;
rStickY = (float)rStick.dy / JOYSTICK_MAX;
printf("(%f, %f) (%f, %f)\n", lStickX, lStickY, rStickX, rStickY);
}
```
At the moment it still follows the ctrulib way where values are passed in raw (dx,dy are just s32s from -0x8000 to 0x8000), though some defines are provided for min/max values for conversion to float.
=> hid: Add hidJoystickRead

nx/include/switch/services/bsd.h, nx/include/switch/types.h, nx/source/runtime/env.c, nx/source/services/bsd.c
This fixes the initalization of the BSD service(s). Without this commit, the bsd services wouldn't send or receive more than 1 byte/s using TCP, as it was issuing ZeroWindow (unbuffered) packets, symptom of a lack of memory.
The following helper functions have been added:
* ~~`bsdGetTransferMemSizeForConfig`, returning the minimal size needed for the transfer memory to be passed to `bsdInitalize` (using any size less than that will cause the abovementionned issue)~~
* `bsdGetDefaultConfig`, returning a reasonable default configuration for the developer to use
* `bsdInitalizeDefault`
The `bsd` service code now manages the transfer memory itself.
`bsdExit` has been added.
Some const-correctness issues have also been made.
=> Make the bsd service work properly

nx/include/switch/gfx/buffer_producer.h, nx/include/switch/services/acc.h, nx/source/gfx/nvgfx.c, nx/source/kernel/random.c, nx/source/runtime/devices/console.c, nx/source/runtime/newlib.c, nx/source/services/applet.c
These occur with a few other warning flags and figured I'd fix them, particularly because a function prototype was exposed in acc.h that doesn't have an implementation (`accountGetSessionService`).
If some others were actually intended to be exposed in headers, just let me know and I'll move them over as opposed to making them static.
=> Silence a few missing prototype warnings

nx/switch_rules
Compile options for switch are too specific to use for generic armv8-a
=> use only one portlibs directory

nx/include/switch/services/hid.h
Add max real value for amplitudes.
Amps > 1.0f are permitted and they are sent as 1.0f.
=> [hidvib] Rename vibration values variables

nx/switch_rules
Adding portlibs bin folder to path so the various config scripts can be used from standard Makefiles
=> add portlibs bin to path

nx/external/bsd/include/netinet/in.h
These macros referenced `__u6_addr.__u6_addr32` where `__u6_addr32` is part of an anonymous union - this fixes compilation errors in apps using these macros.
=> Fix IN6_IS_ADDR macros in netinet/in.h

nx/include/switch/kernel/ipc.h
Adds IpcParsedCommand.NumStaticsOut, IpcParsedCommand.CommandType;
IpcCommandType is a new enum.
=> IPC: Improve information available in IpcParsedCommand

nx/include/switch.h, nx/include/switch/services/fsldr.h, nx/source/services/fsldr.c
Using fsp-ldr in userland requires the fsp-ldr session be available, or fsldrInitialize() will return a failing result.
=> Add fsp-ldr support, Add lr + fsp-ldr to <switch.h>

nx/include/switch/kernel/svc.h
Server handle and client handle were switched in libnx header.
=> Fix definition for svcCreateEvent

nx/source/runtime/devices/fs_dev.c, nx/source/services/fsldr.c, nx/source/services/lr.c
avoid gcc 8.1.0 diagnostics as per https://gcc.gnu.org/onlinedocs/gcc-8.1.0/gcc/Warning-Options.html#index-Wstringop-truncation
=> fix stringop-truncation warnings

nx/source/services/set.c
memset and memcpy requires string.h
=> Add string.h to remove compile error

nx/include/switch/services/fatal.h, nx/source/services/fatal.c
This adds a new "fatalWithType" function, and refactors fatalSimple to call it.
Also adds an appropriate enum for FatalType.
=> Fatal: Make fatalSimple not create report, add FatalType enum

nx/include/switch/kernel/ipc.h, nx/include/switch/result.h
Currently it's hard to use IpcParsedCommand for domain messages.
This fixes that.
=> Improve IpcParsedCommand domain message info.

nx/source/kernel/mutex.c
Currently, mutex unlock will try to exchange the current mutex value with 0, and, if the has listeners flag is set, it calls the ArbitrateUnlock svc. However, between the time that the mutex value is set to 0 and ArbitrateUnlock runs, its possible that mutexLock is called before ArbitrateUnlock writes the new thread handle. Basically, this scenario is possible currently:
(Consider that Thread A, B and C are all running at different cores).
- Thread A tries to acquire the mutex, and succeeds as no thread is holding it yet.
- Thread C tries to acquire the mutex, but fails and waits (calling svcAbitrateLock) because thread A is already holding it.
- Thread A calls mutexUnlock, sync_lock_test_and_set writes 0 at mutex address.
- Thread B calls mutexLock, since the value at the mutex address …
=> Fix mutexUnlock

nx/external/bsd/include/netdb.h
Fixes compilation error that complains about unknown type `socklen_t` when including `netdb.h` anywhere. 
The original FreeBSD `netdb.h` has this typedef: https://github.com/freebsd/freebsd/blob/master/include/netdb.h#L80
=> Re-introduce socklen_t definition to netdb.h

nx/source/kernel/detect.c
Compilers have that annoying property to reorder store ops. This introduces a data race in detect.c's _CacheValues. The following disassembler output shows that in this instance, the compiled code writes to g_HasCached before writing to g_IsAbove400:
```
.text._CacheValues:00000000000000D8  MOV   X1, #0x14
.text._CacheValues:00000000000000DC  BL    svcGetInfo
.text._CacheValues:00000000000000E0  LDRB  W2, [X25,#g_IsAbove400@PAGEOFF]
.text._CacheValues:00000000000000E4  ADRP  X3, #g_IsAbove500@PAGE
.text._CacheValues:00000000000000E8  CMP   W0, W22
.text._CacheValues:00000000000000EC  CSET  W4, NE
.text._CacheValues:00000000000000F0  MOV   W5, #1
.text._CacheValues:00000000000000F4  MOV   X0, X20
.text._CacheValues:00000000000000F8  LDRB  W1, [X24,#g_IsAbove300@PAGEOFF] …
```
=> Fix data race by reordering in detect.c's _CacheValues

nx/source/services/hid.c
`LAYOUT_PROCONTROLLER` is a value of zero, so the bitwise AND condition here would always be false (`TYPE_PROCONTROLLER`, on the other hand is a value of 1)
=> hid: Correct bitwise AND for pro controllers in hidInitializeVibrationDevices()

nx/source/services/nifm.c
Untested, however, CreateGeneralServiceOld was not added until 3.0.0. This means 2.0.0->2.3.0 would try to call a non-existent cmd.
=> Fixed nifm not initializing properly for > 1.0.0 < 3.0.0

nx/include/switch/nvidia/ioctl.h, nx/include/switch/services/fsldr.h, nx/include/switch/services/ns.h, nx/source/services/csrng.c, nx/source/services/fsldr.c, nx/source/services/ns.c
Gets rid of trivial warnings caused by headers not being included into the relevant .c file, empty parameter lists missing void, or functions missing a prototype in the header.
I've included the Nvidia ioctl prototypes that were missing, but can omit those if that interface is still in flux.
=> Resolve trivial -Wmissing-prototypes warnings

nx/source/kernel/random.c
This macro is only ever used with const input data within `chachaInit()` a little further down at line 68, which causes `-Wcast-qual` warnings. This is trivial enough to fix by preserving the qualifier within the cast.
=> kernel/random: Avoid casting away const in the U8TO32_LITTLE macro

nx/include/switch/services/psm.h, nx/source/services/psm.c
Don't know if the names are correct but the only thing that returns ChargerType 1 is the official charging cable (be it directly or through the dock)--every other USB-C device I've plugged in returns 2.
=> Add psm:GetChargerType

nx/include/switch/services/applet.h, nx/source/services/applet.c
Add the [Exit](http://switchbrew.org/index.php/AM_services#Exit) command to applet. This enables exiting an application back to the home menu. It was named `appletSelfExit()` instead of `appletExit()` since `appletExit()` already existed.
=> applet: Add appletSelfExit()

nx/include/switch/runtime/devices/console.h, nx/source/runtime/devices/console.c, nx/source/runtime/devices/console_sw.c
*to maintainers: do not merge, I will do it myself once it's reviewed/approved*
- Added ConsoleRenderer interface, which abstracts all relevant operations needed to set up and write characters to a text mode display
- ConsoleFont now has tileWidth/tileHeight parameters
- PrintConsole now holds a pointer to a ConsoleRenderer
- Added consoleExit for deinitializing the console
- Added consoleUpdate for updating the display every frame
- Corrected lots of obsolete/outdated comments
- Separated console software renderer into its own file (console_sw.c)
- Added getDefaultConsoleRenderer weak function, for selecting the default console renderer when none (NULL) is specified in PrintConsole
- Software renderer now takes care of gfxInitDefault/gfxExit
- All these changes are backwards compatible …
=> Refactor console device (needed to support GPU-rendered console in the future)

nx/include/switch/services/applet.h, nx/source/services/applet.c
This will permit to be able to be notified on exit by:
- hooking on exit
- being able to delay exit until decided
Here is an example of use: https://gist.github.com/p-sam/bd39c9a084cfd45c793d0bdfe2b8f2c7
Homebrew would be able to use this moment to flush state, and close handles. (eg: RetroArch flushing SaveRAM)
=> add an exit request hook type, allow to delay exit

nx/include/switch/kernel/ipc.h, nx/include/switch/services/sm.h, nx/source/services/fs.c, nx/source/services/fsldr.c
Adds new serviceIpcPrepareHeader, serviceIpcParse, serviceCreateSubservice functions.
Causes a breaking (but necessary) change to ipcParseForDomain.
Makes fsInitialize() call serviceConvertToDomain(), resulting in all FS commands using domain object IDs.
=> Make FS use domains.

nx/external/bsd/include/netinet/in.h
I'm not sure what is the cause of this missing declarations, as they are defined in <sys/types.h>. What i know for sure is this commit fix a few library/application build i'm currently using privately.
=> netinet: fix missing declarations (?)

nx/include/switch/runtime/devices/fs_dev.h, nx/include/switch/services/fs.h, nx/source/runtime/devices/fs_dev.c, nx/source/services/fs.c
This adds fsFsQueryEntry, an IFileSystem command added in 4.0.0.
It also adds a helper for using fsFsQueryEntry to set the archive bit. Please note, HOS returns 0x202 when calling SetArchiveBit on a file (and only allows setting on directories). This should be fine, though, because HOS only assigns special meaning to the archive bit for directories.
=> fs: Add fsFsQueryEntry (and fsFsSetArchiveBit helper)

nx/include/switch/kernel/svc.h, nx/source/kernel/svc.s
0x2A corresponds to svcFlushEntireDataCache, while 0x2B corresponds to svcFlushDataCache.
=> kernel/svc: Correct SVC instruction values for svcMapPhysicalMemory and svcUnmapPhysicalMemory

nx/include/switch/services/applet.h, nx/source/services/applet.c
I added the missing applet focus states and handling modes in `applet.h`.
- The unknown focus state is indeed because of an open LibraryApplet
- Suspend1 is now SuspendHomeSleep, as it only suspends when the HOME menu is open or the console is sleeping
- Suspend2 is now SuspendHomeSleepNotify, as it only suspends when the HOME menu is open or the console is sleeping while still recieving the OnFocusState hook
- Suspend3 is now AlwaysSuspend, as it always suspends the applet regardless of the reason (HOME menu or LibraryApplet)
=> Add missing applet focus states and handling modes

nx/external/bsd/include/sys/poll.h
See https://github.com/devkitPro/pacman-packages/pull/62#discussion_r241958388 for reasoning. linux and osx have both headers which means some software will be easier to port if we have both headers too.
=> redirect sys/poll.h to poll.h for compatibility

nx/source/runtime/devices/console.c
if '\n' is printed at windowWidth + 1, consoleNewRow() will be executed twice.
Example:
```
printf("%s\n", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
```
80 'a' will be printed, then new line because the cursor is a the end of the line, and then our '\n' will be printed
=> fix print \n twice

nx/source/services/hwopus.c
This is a flag that determines whether or not a request to reset the decoder context should occur prior to decoding. This is an analogue to the libopus:
```cpp
opus_decoder_ctl(decoder, OPUS_RESET_STATE);
```
which is generally used when switching streams to keep decoder state consistent.
=> hwopus: Provide a better name for the flag parameter of _hwopusDecodeInterleaved()

nx/include/switch/services/pm.h, nx/source/services/pm.c
This is necessary in order to support a shim for service extension without having two sessions active.
=> pm: Add pmdmntGetServiceSession()

nx/include/switch/services/hwopus.h
This second member indicates the Opus encoder's entropy coder's final range. While nothing in the service actually does anything with the final range as far as I can tell, this is specified within [RFC 6716](https://tools.ietf.org/html/rfc6716) (see section "6. Conformance") as a means of ensuring decoder conformance. It states as follows:
>
> In addition, a compliant decoder implementation MUST have
> the same final range decoder state as that of the reference decoder.
>
So what is likely done when performing compliance testing is the data is encoded, and then the final range of the encoder is sent via this header, then during decoding, the final range would be checked against to ensure that it's valid (though this doesn't seem to actually be checked anywhere in the hwopus-related code …
=> hwopus: Document second member of HwopusHeader

nx/include/switch.h, nx/include/switch/services/wlaninf.h, nx/source/services/wlaninf.c
`wlanGetState` allows to know if WLAN is connected or not. It can be in a disconnected state either because of airplane mode, or because no known network is in reach. `nifmIsWirelessCommunicationEnabled` can be used to know if airplane mode is enabled or not.
`wlanGetRSSI` allows to get the WiFi signal strength, from -30db to -90db (on a logarithmic scale). If WiFi is not connected, result `0x26bd` will be returned.
=> Implement wlanGetState and wlanGetRSSI

nx/include/switch/services/nifm.h, nx/source/services/nifm.c
`nifmGetInternetConnectionStatus` allows to get internet connection type (Wi-Fi or Ethernet), status (connecting or connected) and strength in bars (from 0 to 3), which is better than RSSI to display to users.
The call will fail with `0xd46ed` is the console is neither connecting or connected to a network.
=> Implemented nifmGetInternetConnectionStatus

nx/include/switch/runtime/devices/romfs_dev.h, nx/include/switch/services/fs.h, nx/source/runtime/devices/fs_dev.c, nx/source/runtime/devices/romfs_dev.c, nx/source/services/fs.c
This re-does the romfs API to allow specifying mount name.
It also adds a helper for mounting a system data archive, and fsOpenDataStorageByDataId.
=> romfs: refactor to allow specifying mount name

nx/include/switch/kernel/rwlock.h, nx/source/kernel/rwlock.c
This one is superior to the previous because it is write-preferring.
=> rwlock: Move over to condvar implementation.

nx/source/runtime/devices/fs_dev.c
This fixes mkdir() errno value when the given path already exists.
=> add 0x402 (path exists) => EEXIST mapping in fs_dev

nx/include/switch/kernel/ipc.h
In C++ projects with higher warning levels, this header can cause some missing initializer warnings to leak over. This silences those from occurring.
=> kernel/ipc: Resolve missing initializer warnings

nx/include/switch/services/ldr.h
This is an issue in both libnx and atmosphere...
=> loader: fix LoaderModuleInfo definition

nx/include/switch/kernel/svc.h, nx/source/kernel/svc.s
how do we still have unimplemented svcs in 2019
=> Implement svcQueryProcessMemory

nx/include/switch/services/ldr.h, nx/include/switch/services/ro.h, nx/source/services/ldr.c, nx/source/services/ro.c
This updates ro services to the modern day.
Adds ro:1 (and new ldrRoLoadNrrEx command added in 7.0.0)
Also fixes roDmnt sending the wrong kind of IPC buffer.
=> ro: Implement ro:1, add ldrRoLoadNrrEx, fix roDmnt

nx/source/services/sm.c
This matches official software behavior, and is necessary for FIRM sysmodules.
=> sm: add retry loop in smInitialize

nx/include/switch/services/spl.h, nx/source/services/spl.c
Also checks HosVersionBefore(3, 0, 0) before calling them.
=> spl: fix BootReason command names

nx/include/switch/runtime/devices/fs_dev.h, nx/source/runtime/devices/fs_dev.c
Adds fsdevGetLastResult, which returns a thread local Result updated by every call to fsdev_translate_error.
Also changes fsdev_translate_error to return EIO instead of raw results, when not translatable.
=> fsdev: add way of getting last returned result.

nx/source/runtime/devices/romfs_dev.c
->setup was never being written.
=> romfs_dev: fix unmounting/corruption when mounting multiple.

nx/include/switch/runtime/devices/fs_dev.h, nx/include/switch/services/fs.h, nx/source/runtime/devices/fs_dev.c, nx/source/runtime/devices/romfs_dev.c, nx/source/services/fs.c
Fixes API for fsFsCreateFile, fsFsReadFile, fsFsWriteFile.
Fixes missing flag for DIROPEN, adds missing flags for CREATE/READ/WRITE.
Adds missing *OperateRange commands.
Adds missing fsOpenFileSystemWithPatch command.
Adds fsdevCreateFile helper to create file with flags via stdio-paths.
=> fs: fix file/storage API, add fsdevCreateFile, add fsOpenFileSystemWithPatch.

nx/include/switch/services/fs.h, nx/include/switch/services/ncm.h, nx/source/services/fs.c, nx/source/services/ncm.c
Required for NCM reimplementation. Please note that the RightsId struct had to be moved from the NCM header to the FS header as they both rely on it, and the NCM header already depends on the FS header. Leaving it as-is would lead to a circular dependency, plus I believe it's more suitable for the FS header anyway.
=> Implement fsOpenContentStorageFileSystem, fsGetRightsIdByPath & fsGetRightsIdAndKeyGenerationByPath

nx/include/switch/services/set.h, nx/source/services/set.c
Implements nn::settings::ISystemSettingsServer commands 77 & 78.
https://reswitched.github.io/SwIPC/ifaces.html#nn::settings::ISystemSettingsServer(77)
https://reswitched.github.io/SwIPC/ifaces.html#nn::settings::ISystemSettingsServer(78)
Useful for apps that might want to display or set the console's nickname.
=> Implement setsys GetDeviceNickname/SetDeviceNickname

nx/source/runtime/devices/romfs_dev.c
Not sure if this was somehow intended, tbh.
=> Remove RomFS devoptab device on unmount.

nx/include/switch/services/sm.h, nx/include/switch/services/smm.h, nx/source/services/sm.c, nx/source/services/smm.c
Adds `Service*smGetServiceSession()` and `Service*smManagerGetServiceSession()`.
This exposes Services usable to talk to sm/sm:m the same way as other libnx services (fs, etc).
sm had to be refactored to use Service * instead of a raw handle to support this.
This is useful because it allows for extensions to use the Services without having to duplicate sessions/handles.
=> sm/smm: Add GetServiceSession

nx/include/switch/services/time.h, nx/source/services/time.c
This PR adds timeGetDeviceLocationName, timeSetDeviceLocationName, timeGetTotalLocationNameCount, timeLoadLocationNameList, timeLoadTimeZoneRule, timeToPosixTime, timeToPosixTimeWithMyRule, and timeToCalendarTime.
=> Add more ITimeZoneService related commands

nx/include/switch/services/fs.h, nx/source/services/fs.c
As per title. Needed for reimplementing any sysmodule with savedata.
=> Implement fsCreateSaveDataFileSystemBySystemSaveDataId (and wrappers) + fsDisableAutoSaveDataCreation

nx/source/services/vi.c
Official code passes 1 to GetDisplayService when type is system or manager.
This gives the resulting service elevated permissions (for example, this greatly increases the maximum LayerZ that one can draw to).
=> vi: fix manager/system service init

nx/include/switch/kernel/svc.h
svcGetInfo uses an u32 for id0 in the kernel (which moves W1 and not X1).
=> svcGetInfo id0 should be an u32

nx/source/runtime/devices/romfs_dev.c
Before, only the first letters of the mount name had to match, so that if you had a romfs mounted at `romfs` and tried to unmount `romfshhhhhh` it would still unmount `romfs`
=> Require whole mount name to match when finding a romfs

nx/include/switch/services/ncm.h
As per title. Noticed this was missed in my previous changes.
=> ncm: Use u8 rather than actual types to ensure correct struct sizes

nx/source/kernel/virtmem.c
libnx checks size directly against region size, without accounting for offset into memory region. Due to the 0x1000 addition of guard pages, this issue causes libnx to decide a region is acceptable for reservation when it is 0x1000 too small (or causes other bad checks if the region is the first one considered).
=> virtmem: fix incorrect bounds check

README.md, nx/include/switch/services/hiddbg.h, nx/source/services/hiddbg.c
When low memory usage is important, functions like `hiddbgDumpHdlsStates()` and `hiddbgDumpHdlsNpadAssignmentState()` won't be efficient as they copy the entire struct.
Since there is no need to copy the struct at all, the function `hiddbgGetWorkBufferTransferMemoryAddress()` lets the user read from transfer memory directly.
=> hiddbg: Add a function to get Hdls' TransferMemory

nx/include/switch/services/set.h, nx/source/services/set.c
Adds support for set:sys commmands `IsUserSystemClockAutomaticCorrectionEnabled` and `SetUserSystemClockAutomaticCorrectionEnabled`.
https://switchbrew.org/wiki/Settings_services#set:sys
While I do not have a way to verify that these use `bool`s myself, [SwIPC](https://reswitched.github.io/SwIPC/ifaces.html#nn::settings::ISystemSettingsServer(60)) claims they do, and my own past testing shows that `bools` seem to work fine.
=> Add support for setting/getting the Internet time sync flag.

nx/include/switch/services/fs.h
ref https://github.com/Thealexbarney/LibHac/blob/f3b5cad94b1d0ce5a1799048172f99e5fd7c3f59/src/LibHac/FsService/FileSystemProxy.cs#L178
in testing, present in the following saves in 9.0.1:
```
save id              flags owner id
8000000000000010     1100  010000000000001e
8000000000000050     1000  0100000000000009
80000000000000a0     1000  010000000000000c
80000000000000a1     1000  010000000000000c
80000000000000a2     1000  010000000000000c
8000000000000190     1000  0100000000000031
```
makes sense for account, settings, prepo saves (not sure why glue)
=> Add FsSaveDataFlag for BIT(3)

nx/include/switch/kernel/rwlock.h, nx/source/kernel/rwlock.c
Implements rwlockTryReadLock and rwlockTryWriteLock.
Also implements rwlockIsWriteLockHeldByCurrentThread and rwlockIsOwnedByCurrentThread.
Also re-designs RwLock to have semantics identical toNintendo's (nn::os::ReaderWriterLock). 
The upshot is mostly that the lock is now fully recursive/write-preferring.
=> rwlock: revamp completely

nx/include/switch/runtime/devices/fs_dev.h, nx/source/runtime/devices/fs_dev.c
Fixes fsdev_fixpath() returning NULL when a FsFileSystem object is mounted using a device name with a trailing colon.
=> Update documentation about fsdevMountDevice() to inform about trailing colons in device names.

nx/include/switch/services/ts.h
Avert some confusion about the temperature locations.
HOS uses TMP451 IC's internal thermistor for PCB temp readings
External is connected to a thermistor to SoC's package temp pins, so SoC temp readings.
=> ts: Add temperature location comments

nx/include/switch/services/hid.h
I know you guys have changed JOYSTICK_MAX in one of the commits (b83ddf8157e7aef37159aaff9e0b40b137339504) after getting complaints in the IRC chat. There is more to this problem, where games like Resident Evil 4 and (i think) Assassin's Creed 3 make assertions on joystick values being at least -32767 and at most 32767 and aborting if it's outside the range of acceptable values. I'm guesing they take those values from the SDK so the values in libnx should be updated accordingly.
=> hid: Update the value for JOYSTICK_MIN

nx/include/switch/kernel/svc.h, nx/source/kernel/svc.s, nx/source/kernel/thread.c
This corrects a number of SVC definitions, and fixes a bug in the stub for svcGetThreadCoreMask.
=> svc: fix definitions to better match kernel

nx/include/switch/services/nfc.h, nx/source/services/nfc.c
OpenApplicationArea command doesn't take an out u32 value
=> Fix nfp OpenApplicationArea command

nx/source/services/psc.c
This fixes the ability to use psc:m on exactly 5.1.0.
=> psc: correct version for pscPmModuleAcknowledge

nx/source/runtime/devices/fs_dev.c, nx/source/runtime/devices/romfs_dev.c
lstat is supported by devoptab, but we don't expose it
symlinks aren't a thing on fat32/exfat so we can just alias lstat to stat.
=> add lstat to fs_dev and romfs_dev

nx/source/runtime/devices/romfs_dev.c
stat is defined to return 0 or -1, this is probably a typo of -1?
=> fix return value of romfs_stat for non-existent files/directories

nx/include/switch/services/hiddbg.h, nx/source/services/hiddbg.c
This is needed to prevent home button presses when running system updater homebrew from applet mode.
=> hiddbg: implement DeactivateHomeButton

nx/source/services/ldr.c
SetProgramArguments no longer takes in u32 for arguments size and just uses the InBuffer size.
This updates client code accordingly.
=> ldr: update SetProgramArguments for 11.0.0 abi change

nx/include/switch/kernel/svc.h
It should be 2MB, not 32MB.
https://github.com/Atmosphere-NX/Atmosphere/blob/c45088d1cda2d0bcb6a7fb35f8c2d826728ed730/libraries/libvapours/include/vapours/svc/svc_types_common.hpp#L119
=> Fix svcSetHeapSize error in comment section

nx/include/switch/services/fs.h, nx/source/services/fs.c
These are needed to easily generate custom `FsSaveDataType_Cache` savedata entries.
Unlike normal savedata, cache savedata size can't be retrieved from the NACP, which means it's necessary to calculate its required size. One could then create a cache savedata entry larger than the calculated size, which is simpler than having to resize the existent save each time new data is written to it.
=> fs: Added fsCreateSaveDataFileSystem(), fsDeleteSaveDataFileSystem() and fsDeleteSaveDataFileSystemBySaveDataAttribute().

nx/include/switch/runtime/devices/socket.h, nx/include/switch/services/bsd.h
There is a small typo in nx/include/switch/runtime/devices/socket.h, nx/include/switch/services/bsd.h.
Should read `receive` rather than `recieve`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, recieve -> receive

nx/include/switch/services/psc.h, nx/source/services/psc.c
whoops, this was actually u32 the whole time (it's PmModuleIds).
=> psc: fix dependency argument on init

nx/include/switch/sf/cmif.h, nx/include/switch/sf/service.h
We didn't support null output objects or auto-select-with-mode buffers.
=> sf: add serialization fixes necessary for htcs

nx/include/switch/services/psm.h, nx/source/services/psm.c
Update the charger definitions to match what's on the wiki: https://switchbrew.org/wiki/PTM_services#ChargerType
I'll update switch-examples with a matching fix if no changes need to be made to this PR.
=> psm: Fix charger definitions

nx/source/services/pgl.c
tipc doesn't stable-sort arguments by alignment, it appears to do no sorting at all.
=> pgl: fix argument order for LaunchProgram on 12.x

nx/include/switch/audio/driver.h, nx/source/audio/voice.c
This pull request adds `audrvVoiceIsPaused` to libnx. I've been kind of wanting this to be a thing for a while, since libctru has `ndspChnIsPaused` as an equivalent to this.
https://streamable.com/djoa9f
[audren-simple-is-paused.zip](https://github.com/switchbrew/libnx/files/6378963/audren-simple-is-paused.zip)
=> audrv: add audrvVoiceIsPaused

nx/include/switch/applets/swkbd.h, nx/source/applets/swkbd.c
- Provides more accurate descriptions for SwkbdInline State
- stringLenMaxExt -> stringLenMin
- unk_x20 -> stringLenMax and unk_x24 -> stringLenMin in SwkbdAppearArg and add setters for these 2 struct members.
=> swkbd: Fix several swkbd enums and structs

nx/include/switch/services/btdrv.h
As per the title. Adds missing event info definitions for firmware specific changes to the connection field of both `BtdrvEventInfo` and `BtdrvHidEventInfo` structs.
=> Update core bluetooth and hid connection event info to support all firmwares

nx/include/switch/services/btm_types.h, nx/source/services/btm.c
This adds partial definitions for BtmDeviceCondition. This structure has changed size three times over the course of various firmware updates. I wasn't sure how to best handle the different struct versions in a way that fits with the rest of the libnx codebase. Thoughts and ideas are welcome.
=> btm: add DeviceCondition definitions

nx/source/kernel/thread.c
This changes threadInit to set thread/argument fields before calling svcCreateThread().
This is desirable because svcCreateThread will cause an attached debugger to receive a DebugEvent, at which point the debugger will begin parsing information about the thread/etc.
As is, it is impossible for the debugger to reconstruct information about the thread on creation; by setting the fields appropriately beforehand, they can be parsed from the ThreadEntryArgs etc.
=> thread: set arguments/fields before CreateThread

nx/include/switch/services/btdrv.h, nx/source/services/btdrv.c
BluetoothSspVariant is 32-bit on 12.0.0. This fixes the btpair application from [nx-btred](https://github.com/plutooo/nx-btred) being unable to pair when compiled with current libnx.
=> btdrv: fix btdrvRespondToSspRequest for 12.0.0

nx/include/switch/kernel/svc.h, nx/source/kernel/svc.s
This adds the new svc:: stuff to userspace.
It doesn't remove SvcMapDeviceAddressSpace, but I think that's probably okay/we can leave it in. It does add a note that it's 1.0.0-12.1.0 (and non-mesosphere, naturally).
=> svc: add 13.0.0 svc changes

nx/include/switch/services/hiddbg.h, nx/source/services/hiddbg.c
`hiddbgIsHdlsVirtualDeviceAttached` makes use of the `DumpHdlsStates` ipc cmd, and args should be adapted for 13.0.0 like it was done on `hiddbgDumpHdlsStates`
=> hiddbg: fix IsHdlsVirtualDeviceAttached for 13.0.0

nx/include/switch/services/hidsys.h, nx/source/services/hidsys.c
Adds missing service wrappers for the following UniquePad functions
- AcquireUniquePadConnectionEventHandle
- GetUniquePadBluetoothAddress
- DisconnectUniquePad
- GetUniquePadType
- GetUniquePadInterface
- GetUniquePadControllerNumber
=> hidsys: add some missing unique pad service wrappers

nx/include/switch/kernel/svc.h
Here attr has the IsDeviceMapped bit but device_refcount is 0.
See also https://github.com/Atmosphere-NX/Atmosphere/blob/master/libraries/libvapours/include/vapours/svc/svc_types_base.hpp#L23-L32
=> svc: Fix MemoryInfo field order

nx/include/switch/services/ts.h, nx/source/services/ts.c
14.0.0 removed support for tsGetTemperatureMilliC.
It's reflected on switchbrew wiki.
https://switchbrew.org/wiki/PTM_services#ts
=> ts: Update tsGetTemperatureMilliC

nx/source/kernel/svc.s
Initial PR used wrong IDs for the io region svcs because of copy/paste error, this fixes them to the right ids.
=> svc: fix wrong ids for (Un)MapIoRegion

nx/source/arm/cache.s
I don't have a switch but on r-pi4 it's easy to reproduce problems
without this Instruction Synchronization Barrier. Better be safe than
having "fun" dealing with super rare crashes.
=> cache: need an isb barrier on icache invalidate

nx/include/switch/applets/swkbd.h, nx/source/applets/swkbd.c
Recent versions of the sdk appear to have fixed the behavior that was reproduced previously. Below code from 11.4.3.0:
I took advantage of this to fix some typos
=> Fix calculation of the inline swkbd touch area

nx/source/services/bpc.c
This was not actually writing the output u8 due to typo, breaking power button detection for anything built with libnx since commit d42ddeff783ec9ae92ea38c4b7857f5c81a1bebc was included.
Note the original typo was PR'd by me.
=> bpc: fix GetSleepButtonState/GetPowerButton

nx/include/switch/services/ncm_types.h
* Added `NcmContentMetaType_DataPatch`.
* Added `NcmContentMetaAttribute_Compacted`.
* Updated `NcmContentInfo`:
* Replaced `size` field with `size_low` and `size_high`, which are easier to work with.
* Added new `attr` field.
* Updated `NcmAddOnContentMetaExtendedHeader`:
* Added new `content_accessibilities` and `data_patch_id` fields.
* Renamed previous `NcmAddOnContentMetaExtendedHeader` to `NcmLegacyAddOnContentMetaExtendedHeader`.
* Added `NcmDataPatchMetaExtendedHeader`.
* Added `ncmContentInfoSizeToU64` and `ncmU64ToContentInfoSize` methods to easily work with size fields from `NcmContentInfo` objects.
=> Update ncm_types to 15.0.0.

nx/include/switch/services/audctl.h, nx/source/services/audctl.c
These functions take a signed int, ranging from 0 to 15.
MasterVolume functions, on the other hand, take a float from 0 to 128.
=> audctl: fix TargetVolume functions

nx/include/switch/services/hiddbg.h, nx/source/services/hiddbg.c
The current version of `hiddbgAttachHdlsWorkBuffer` is incompatible with sysmodules using libstratosphere due to the libnx memory allocations in `tmemCreate`.  This modifies the existing function to create a transfer memory from an optional user-supplied buffer using `tmemCreateFromMemory` instead.
I wasn't sure whether breaking the existing API by adding the additional parameters was a good idea, but this seems like the most straightforward solution.
=> hiddbg: modify hiddbgAttachHdlsWorkBuffer to accept a user-supplied buffer and size

nx/include/switch/services/audctl.h, nx/include/switch/services/auddev.h, nx/source/services/audctl.c, nx/source/services/auddev.c
`auddevGetActiveAudioDeviceName` does not distinguish between jack and bluetooth connected headphones, however `audctlGetActiveOutputTarget` was only added by 13.0 (with bluetooth audio functionality).
=> Audio: add helpers to query the active device

nx/include/switch/services/fs.h, nx/include/switch/services/fsldr.h, nx/include/switch/services/ncm.h, nx/include/switch/services/ncm_types.h, nx/include/switch/services/vi.h, nx/source/services/fs.c, nx/source/services/fsldr.c, nx/source/services/ncm.c, nx/source/services/vi.c
This PR shouldn't be merged yet, and is for getting in anything libnx needs for 16.0.0 support.
=> Add changes for baseline 16.0.0 support

nx/external/bsd/include/sys/socket.h
Latest version of Moonlight-common-c library uses this definitions, so it is impossible to compile app without them.
To be honest I am not fully understand what they are doing, I've just copy-pasted them from Apple's /sys/socket.h file with some changes, cause it uses some Darwin types which of course not presented on Switch.
Anyway after these changes I was able to compile Moonlight it it worked perfectly.
=> Added some definitions to /sys/socket.h

nx/include/switch/services/applet.h, nx/source/services/applet.c
This allows waiting for applet messages using a custom event loop (as opposed to using appletMainLoop).
=> applet: add appletGetMessageEvent

nx/include/switch/runtime/devices/usb_comms.h, nx/source/runtime/devices/usb_comms.c
This adds an asynchronous API to usbComms with minimal error handling, for use as an alternative to the blocking versions. This also enables setting the VID:PID reported by the device during initialization.
=> usbcomms: API improvements

nx/source/runtime/devices/fs_dev.c
Recent newlib updates removed trailing slash from cwd. This compensates for that when building paths,
=> add missing separator to local path

nx/include/switch/services/mii.h, nx/include/switch/services/nfc.h, nx/source/services/nfc.c
I need to perform a hardware test, so I require all functions of this service to be available across all interfaces. This is my first time committing a major change, so please let me know if anything is incorrect or if there are any issues.
This pull request fully implements nfc, nfp:system, nfp:debug, and nfc:mf:u. Additionally, it fixes some minor bugs in the previous implementations.
=> service: nfc: Implement all interfaces and function calls

nx/source/services/nfc.c
Missed this function in previous commit. Mifare should be functional now.
=> service: nfc: Add mifare guard

nx/include/switch/sf/service.h, nx/source/services/capsc.c, nx/source/services/fs.c, nx/source/services/ns.c
I got very frustrated just now by failing to dereference an output pointer argument, so I added a static assertion that the input/output to the service dispatch macros aren't pointers.
This immediately caught three cases where we failed to invoke dispatch function correctly, so this also fixes those.
=> service: Static assert arguments aren't pointers to prevent failure-to-deref

nx/source/crypto/aes_cbc.c
We ran into this issue in nxdumptool when decrypting the card header encryption target data from an inserted gamecard, which made us think that Nintendo added a [new field to the data](https://github.com/DarkMatterCore/nxdumptool/blob/8f75b6b923126fa3b1e7c72bbf6dcc94f3beefc9/include/core/gamecard.h#L195).
This happens due to a missing XOR operation during individual block decryption. Since the card header encryption target data is 0x70 bytes in the size, the first six blocks are decrypted correctly, while the last block is not.
=> crypto: fix aes-cbc individual block decryption

nx/include/switch/kernel/svc.h, nx/source/kernel/svc.s
This fixes the names for svc::QueryMemoryMapping, svc::MapInsecurePhysicalMemory, svc::UnmapInsecurePhysicalMemory
=> svc: fix query/insecure names

nx/include/switch/applets/error.h, nx/include/switch/applets/swkbd.h, nx/include/switch/applets/web.h, nx/include/switch/display/buffer_producer.h, nx/include/switch/kernel/svc.h, nx/include/switch/kernel/thread.h, nx/include/switch/runtime/diag.h, nx/include/switch/runtime/env.h, nx/include/switch/services/fatal.h, nx/include/switch/services/miiimg.h, nx/include/switch/services/nfc.h, nx/include/switch/services/set.h, nx/include/switch/services/usb.h, nx/include/switch/services/usbhs.h, nx/include/switch/types.h, nx/source/runtime/env.c, nx/source/runtime/init.c, nx/source/runtime/newlib.c, nx/source/runtime/ringcon.c, nx/source/services/applet.c, nx/source/services/fatal.c
Hello.
The ``PACKED`` macro conflicts with fmtlib 10. I prefixed your macros with ``NX_``.
This is the same issue fixed in libctru recently: 
- https://github.com/devkitPro/libctru/issues/530
- https://github.com/devkitPro/libctru/pull/532
Not sure if renaming ``NORETURN`` is a bad idea (compat issues?). I can undo this when you dislike it.
``IGNORE_ARG`` and ``DEPRECATED`` look unused in libnx.
=> Add NX_ prefix to PACKED, NORETURN, IGNORE_ARG and DEPRECATED macros

nx/include/switch/services/fs.h, nx/source/services/fs.c
i wasn't sure if the `version` field should be a bitfield or just a u32. if we keep it a u32, should i comment how to extract the version as it might not be obvious to the dev, as they may try to use `HOSVER_X` macros on it
```c
const u8 relstep = (update_partition_info.version >> 0)  & 0xFFFF;
const u8 micro   = (update_partition_info.version >> 16) & 0x000F;
const u8 minor   = (update_partition_info.version >> 20) & 0x003F;
const u8 major   = (update_partition_info.version >> 26) & 0x003F;
```
=> add fsDeviceOperatorGetGameCardUpdatePartitionInfo

nx/source/runtime/init.c
The `exit` routine executed after `main` returned already calls `libc_fini_array`. Calling it again within `__libnx_exit` calls the destructor for static objects a second time which results in a segfault when static/global objects are used in a program.
=> Fix: avoid segfault at static destructors

nx/include/switch/services/fs.h, nx/source/services/fs.c
Example usage:
```c
int main(int argc, char *argv[])
{
consoleInit(NULL);
PadState pad;
padConfigureInput(1, HidNpadStyleSet_NpadStandard);
padInitializeDefault(&pad);
nsInitialize();
fsInitialize();
FsDeviceOperator deviceOperator;
fsOpenDeviceOperator(&deviceOperator);
FsGameCardHandle gcHandle = {-1};
fsDeviceOperatorGetGameCardHandle(&deviceOperator, &gcHandle);
u8 cert[0x200]; // output
fsDeviceOperatorGetGameCardDeviceCertificate(&deviceOperator, &gcHandle, cert, sizeof(cert), sizeof(cert));
// From application authentication /v%i/challenge endpoint (AAuth, used to authenticate gamecards, they can complete a proprietary challenge to prove they are legit)
u8 seed[15] = {...};
u8 value[16] = {...};
u8 challenge[0x58]; // output
fsDeviceOperatorChallengeCardExistence(&deviceOperator, …
```
=> Implement FS "ChallengeCardExistence" and "GetGameCardDeviceCertificate"

nx/include/switch/nvidia/ioctl.h, nx/source/nvidia/ioctl/nvchannel.c
The version check was accidentally inverted in SET_CLK_RATE.
These are used for video engines and VIC.
=> nvchannel: Fix SET_CLK_RATE, implement GET_CLK_RATE and SET_SUBMIT_TIMEOUT

nx/include/switch/kernel/svc.h, nx/include/switch/services/hidsys.h, nx/include/switch/services/ns.h, nx/source/kernel/virtmem.c, nx/source/services/hidsys.c, nx/source/services/ns.c
This adds version checking to removed commands, and adds the new info types (we apparently never added 16.0.0's IoRegionHint).
The hidsys commands can be cloned to hiddbg, not sure how that should be handled though?
=> Basic support for 18.0.0

nx/include/switch/services/hid.h, nx/source/services/hid.c
This adds the remaining undefined `*SharedMemoryFormat` structures, plus functions for grabbing the state of the system buttons (home, capture, sleep) from shared memory.
To aid with verification, I checked all the struct sizes with  `static_assert` so you don't have to https://godbolt.org/z/3eMxxEh8c
=> Add missing hid shared memory structures and accessor functions for system buttons

nx/include/switch/kernel/svc.h, nx/include/switch/services/caps.h, nx/include/switch/services/capsc.h, nx/include/switch/services/fs.h, nx/include/switch/services/ldr.h, nx/source/services/capsc.c, nx/source/services/fs.c, nx/source/services/ldr.c, nx/switch.ld
This pull request shouldn't be merged yet; it will contain all commits necessary for basic atmosphere/libnx functionality on 19.0.0.
=> Basic support for 19.0.0

nx/include/switch/nvidia/ioctl.h, nx/source/nvidia/ioctl/nvchannel.c
The former code worked by chance if users submitted a single syncpt increment. This matches the layout described on the switchbrew wiki, that was fixed some time ago.
=> nvchannel: fix submit ioctl

nx/include/switch/nvidia/fence.h, nx/source/nvidia/fence.c
This is needed eg. to read syncpt values.
=> nvfence: expose nvhost-ctrl fd

nx/include/switch/services/fsldr.h, nx/include/switch/services/fspr.h, nx/include/switch/services/ldr.h, nx/source/services/fsldr.c, nx/source/services/fspr.c, nx/source/services/ldr.c
There may be other stuff that's needed, but this is what was needed to make atmosphere boot.
Noting that @yellows8 mentioned an fsp-pr change I hadn't noticed.
=> Basic support for 20.0.0

nx/include/switch/services/mii.h, nx/include/switch/services/nfc.h, nx/source/services/nfc.c
This improves naming on some structs/fields, and fixes others which had wrong definitions (NfpData currently has the wrong size due to using the wrong mii type).
Removed some DeviceState values that are not exposed through commands, and merged State (all services internally use the same state values).
=> nfp: Improve types and enums

nx/include/switch/services/aud.h, nx/include/switch/services/audout.h, nx/source/services/aud.c, nx/source/services/audout.c
Application use: I use this in [sys-tune](https://github.com/HookedBehemoth/sys-tune/tree/master/sys-tune/source/impl) to allow for per title volume control whilst keeping the master volume the same.
I've tried to match the style of audout.c/h. It is lacking comments, but i think the function names are descriptive enough.
I have a wrapper for common functions as well, but that probably doesn't belong in libnx :)
=> add audout:a audout:d aud:a aud:d

nx/include/switch.h
In #636 i forgot to add aud.h in switch.h, sorry about that.
=> fix missing include in switch.h for aud.h
